# generated by datamodel-codegen:
#   filename:  openapi.json

from __future__ import annotations

from typing import Annotated, Any, Literal

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, RootModel


class ContentType(RootModel[str | None]):
    root: Annotated[str, Field(max_length=1000)] | None = None
    """
    Optional, `application/octet-stream` by default.
    """


class ContentId(RootModel[str | None]):
    root: Annotated[str, Field(max_length=1000)] | None = None
    """
    Optional: makes the attachment an inline image that the HTML names with `cid:`.
    """


class Attachment(BaseModel):
    """
    Une pièce jointe : contenu en base64. Règles (nom, type, taille) : `services.messages`.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    filename: Annotated[str, Field(max_length=1000)]
    """
    Required, 255 characters at most, without a path.
    """
    content: Annotated[str, Field(max_length=7000000)]
    """
    Required, base64.
    """
    content_type: ContentType | None = None
    """
    Optional, `application/octet-stream` by default.
    """
    content_id: ContentId | None = None
    """
    Optional: makes the attachment an inline image that the HTML names with `cid:`.
    """


class WebhookDelivery(BaseModel):
    id: Annotated[str, Field(pattern="^dlv_[0-9a-f]{32}$")]
    event_id: Annotated[str, Field(pattern="^evt_[0-9a-f]{32}$")]
    status: Literal["pending", "delivered", "failed"]
    attempts: int
    last_status_code: int | None
    last_error: str | None
    created_at: AwareDatetime
    delivered_at: AwareDatetime | None


class FieldModel(BaseModel):
    field: Annotated[str, Field(examples=["to[0]"])]
    message: str


class Error1(BaseModel):
    code: Literal[
        "unauthorized",
        "not_found",
        "domain_not_verified",
        "sending_not_allowed",
        "idempotency_conflict",
        "limit_reached",
        "payload_too_large",
        "invalid_request",
        "quota_exceeded",
        "rate_limited",
        "internal_error",
        "method_not_allowed",
        "http_error",
    ]
    """
    The contract: rely on it, and on `fields[].field`, in your code.
    """
    message: str
    """
    Readable text in the language of the `Accept-Language` header (`en` or `fr`; French by default). The wording may change; the status, `code` and `fields[].field` never do.
    """
    fields: list[FieldModel] | None = None


class Error(BaseModel):
    """
    Every error has this shape, without internal detail or received value.
    """

    error: Error1


class MessageAccepted(BaseModel):
    id: Annotated[str, Field(pattern="^msg_[0-9a-f]{32}$")]
    status: Literal["queued", "sent", "delivered", "bounced", "failed"]
    """
    `queued`, or `failed` when ALL recipients are on the suppression list.
    """


class ReplyTo(RootModel[str | None]):
    root: Annotated[str, Field(max_length=1000)] | None = None
    """
    `address` or `Name <address>`.
    """


class StatsPeriod(BaseModel):
    period: AwareDatetime
    accepted: int
    suppressed: int
    delivered: int
    bounced: int
    deferred: int
    expired: int
    complained: int
    opened: int
    clicked: int


class Recipient(BaseModel):
    email: str
    status: Literal["queued", "sent", "delivered", "bounced", "failed", "suppressed"]
    updated_at: AwareDatetime


class Stats(BaseModel):
    granularity: Literal["day", "hour"]
    since: AwareDatetime
    until: AwareDatetime
    data: list[StatsPeriod]
    totals: dict[str, int]
    """
    The same counters, summed.
    """


class AddSuppressionRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    email: Annotated[str, Field(max_length=1000)]


class Tracking(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    opens: bool | None = False
    clicks: bool | None = False


class Data(BaseModel):
    message_id: Annotated[str, Field(pattern="^msg_[0-9a-f]{32}$")]
    recipient: str
    occurred_at: AwareDatetime
    detail: dict[str, Any]
    metadata: dict[str, str]


class WebhookEvent(BaseModel):
    """
    The JSON body Duva sends to your webhook URL for each delivery event.
    """

    id: Annotated[str, Field(pattern="^evt_[0-9a-f]{32}$")]
    type: Literal["delivered", "bounced", "deferred", "expired", "complained", "opened", "clicked"]
    """
    `delivered` (the recipient's server accepted the message), `bounced` (permanent refusal, including one received afterwards), `deferred` (temporary failure: the sending server will retry), `expired` (it gave up after 24 h), `complained` (the recipient reported the message: the address is then suppressed), `opened` and `clicked` (from Duva's tracking, not from the sending server).
    """
    domain: str
    data: Data


class CreateWebhookRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    url: Annotated[str, Field(max_length=3000)]
    events: Annotated[list[str] | None, Field(max_length=20)] = None


class Webhook(BaseModel):
    id: Annotated[str, Field(pattern="^wh_[0-9a-f]{32}$")]
    url: str
    events: list[str]
    status: Literal["active", "disabled"]
    disabled_reason: str | None
    created_at: AwareDatetime
    secret: str | None = None
    """
    The signing secret (`whsec_...`): present ONLY in the response that creates the endpoint.
    """


class WebhookDeliveryList(BaseModel):
    data: list[WebhookDelivery]


class Event(BaseModel):
    id: Annotated[str, Field(pattern="^evt_[0-9a-f]{32}$")]
    type: Literal["delivered", "bounced", "deferred", "expired", "complained", "opened", "clicked"]
    """
    `delivered` (the recipient's server accepted the message), `bounced` (permanent refusal, including one received afterwards), `deferred` (temporary failure: the sending server will retry), `expired` (it gave up after 24 h), `complained` (the recipient reported the message: the address is then suppressed), `opened` and `clicked` (from Duva's tracking, not from the sending server).
    """
    message_id: Annotated[str, Field(pattern="^msg_[0-9a-f]{32}$")]
    recipient: str
    occurred_at: AwareDatetime
    detail: dict[str, Any]
    """
    Chosen fields only: `code`, `enhanced_code`, `message` (external text: never interpret it), `classification`, `attempts`, `feedback_type` for a complaint, `url` for a click. Never the content of the message or its headers.
    """
    metadata: dict[str, str]


class EventPage(BaseModel):
    data: list[Event]
    next_cursor: str | None
    """
    Pass it as `cursor` for the next page; `null` on the last page.
    """


class SendMessageRequest(BaseModel):
    """
    Forme de la requête. Les règles de contenu (adresses, en-têtes...) : `services.messages`.

    `extra="forbid"` : une faute de frappe (`bcc`, `replyto`) est refusée, pas ignorée en silence.
    Les bornes ci-dessous ne servent qu'à limiter le travail avant validation.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    from_: Annotated[str, Field(alias="from", max_length=1000)]
    """
    Required. `address` or `Name <address>`. Its domain MUST be the one in the path (subdomains excluded).
    """
    to: Annotated[list[str], Field(max_length=1000, min_length=1)]
    """
    Required. Bare addresses (no `Name <address>`), de-duplicated case-insensitively. The maximum depends on the plan (5 in the sandbox). One copy per recipient: each sees only their own address.
    """
    subject: Annotated[str, Field(max_length=5000)]
    """
    Required, one line, 998 characters at most, no control characters.
    """
    html: str | None = None
    """
    At least one of `html` and `text`. 2 MB in all. No NUL character.
    """
    text: str | None = None
    """
    At least one of `html` and `text`. 2 MB in all. No NUL character.
    """
    tags: Annotated[list[str] | None, Field(max_length=100)] = None
    """
    10 at most, 64 characters each, no leading or trailing space. De-duplicated.
    """
    tracking: Tracking | None = None
    """
    Open and click tracking, OFF by default. Requires an `html` body and a domain where Duva has enabled tracking, otherwise `422` (field `tracking`).
    """
    reply_to: ReplyTo | None = None
    """
    `address` or `Name <address>`.
    """
    headers: Annotated[dict[str, str] | None, Field(max_length=100)] = None
    """
    20 headers at most, single-line values. Allow-list: `List-Unsubscribe`, `List-Unsubscribe-Post`, `List-Id`, `In-Reply-To`, `References`, `Auto-Submitted`, `Precedence`, `Importance`, `Feedback-ID` and any `X-*` except the reserved prefixes. `From`, `To`, `Cc`, `Bcc`, `Return-Path`, `Message-ID`, `DKIM-Signature`... are refused.
    """
    metadata: Annotated[dict[str, str] | None, Field(max_length=100)] = None
    """
    Text to text, NEVER sent to the recipient: returned by `getMessage`, in each event and in the webhooks of this message. 10 keys at most (letters, digits, `_`, `.`, `-`, 40 characters), values of 500 characters on one line.
    """
    attachments: Annotated[list[Attachment] | None, Field(max_length=100)] = None
    """
    10 at most, 5 MB decoded in all. Executable extensions are refused. Reserved to accounts in production.
    """


class Message(BaseModel):
    id: Annotated[str, Field(pattern="^msg_[0-9a-f]{32}$")]
    status: Literal["queued", "sent", "delivered", "bounced", "failed"]
    """
    That of the least advanced recipient.
    """
    from_: Annotated[str, Field(alias="from")]
    subject: str
    tags: list[str]
    metadata: dict[str, str]
    tracking: Tracking
    created_at: AwareDatetime
    recipients: list[Recipient]


class Suppression(BaseModel):
    email: str
    reason: Literal["bounce", "unsubscribe", "complaint", "manual"]
    """
    `bounce`, `complaint`, `unsubscribe` or `manual`.
    """
    message_id: str | None
    created_at: AwareDatetime


class SuppressionPage(BaseModel):
    data: list[Suppression]
    next_cursor: str | None
    """
    Pass it as `cursor` for the next page; `null` on the last page.
    """


class WebhookList(BaseModel):
    data: list[Webhook]
